name: 'Generate Pretty Changelog'
description: 'Generate a pretty changelog'
inputs:
  use:
    description: 'Type of changelog'
    required: false
  config:
    description: 'Path to config file'
    required: false
    default: 'changelog.yaml'
  token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
outputs:
  changelog:
    description: 'Changelog'
runs:
  using: 'node20'
  main: 'index.js'
