name: Build

on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare
    outputs:
      version: ${{ steps.version.outputs.tag }}
    steps:
      - name: Extract version
        id: version
        run: echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
      - name: Show version
        run: echo ${{ steps.version.outputs.tag }}

  build:
    runs-on: ${{ matrix.runner }}
    name: Build ${{ matrix.os }}/${{ matrix.arch }}
    needs:
      - prepare
    strategy:
      matrix:
        include:
          - { runner: macos-latest,  os: darwin,  arch: amd64 }
          - { runner: ubuntu-latest, os: linux,   arch: amd64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 go build -ldflags "-s -w" -o "$GITHUB_WORKSPACE"/bin/generate-changelog_${{ matrix.os }}_${{ matrix.arch }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: bin/generate-changelog_${{ matrix.os }}_${{ matrix.arch }}
          retention-days: 1

  commit:
    name: Commit
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: bin
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: build changelog"
          commit_author: ${{ github.actor }} <${{ github.actor }}@noreply.github.com>
          branch: master
          tagging_message: 'v1.0.0'
